### PR TITLE
Update PresenceManager.js

### PR DESCRIPTION
**Pull request by Limit11**

### CODE REVIEW

**Comment by jpbberry** [comment]
Sorry but this does not align with our company views and breaks our core values, Censor Bot Co. does not stand for the stance taken in the post.

**Comment by cailanlf** [comment]
I request that you review your decision- it seems like it would positively affect your bot's growth by making it more inclusive.

**Comment by Limit11** [comment]
That ain’t fair

**Comment by jpbberry** [comment]
> I request that you review your decision- it seems like it would positively affect your bot's growth by making it more inclusive.

As previously stated, this breaks our company's core values, and we don't want it to be represented on our public appearance. I as the CEO have decided to shut down this idea as I don't believe it is appropriate nor truthful and would especially rather it not be brought to a public space such as our bot's presence.

**Pull request closed without merging**
